### ISSUE TITLE
Feature: Adding support for blawar digableinc/tinfoil

### ISSUE THREAD

**Issue by tantoinet** [developersu/ns-usbloader#10]
Is there any chance to add support for the [digableinc/tinfoil](https://github.com/digableinc/tinfoil) nice NSP installer?
Also, please mention on the app which Tinfoil should be used.
The UI is excellent but the server side tool called [Nut](https://github.com/blawar/nut) lacks multiplatform support

**Comment by developersu** [comment]
Hey, tantoinet!
1. Nope.
2. [Adubbz/Tinfoil](https://github.com/Adubbz/Tinfoil) version 0.2.1. Any build should be good. I added a link to the one that I use in the Readme file..
3. Thank you ( ^-^). No, Nut also won't be added.

[BTW](https://github.com/developersu/ns-usbloader/issues/8)

**Comment by tantoinet** [comment]
Thanks for the answer. Any reason for not touching it even with a sixty-foot pole? :)
I was wrong about Nut, I don't know how I ignored it, but it's a full python project that has a server.py script that does the same as ns-usbloader. The other part of the project is related to nsp fetching from cdn, which I'm not interested in.

**Comment by developersu** [comment]
Nut and that new Tinfoil have been developed by person with bad reputation. I don't like what he did (and doing) in FOSS world and I'm not interested in his code. It's kinda only my own opinion.
I hope that once I have time, I'll be able to write own ns-side installer %) 
For now I can only recommend you to try using GoldLeaf 0.5. I understand that you have issues with TF and GL is not perfect, but unfortunately there is no silver bullet for the moment.

And thanks for feedback ;)
