### ISSUE TITLE
Replace the udev rule [GROUP="plugdev"] with [TAG+="uaccess"]

### ISSUE THREAD

**Issue by daniarla** [developersu/ns-usbloader#102]
The first time that I used the package from the AUR I had a lot of problems uploading files through usb, I had no access.
I tried to configure the udev rules to allow the usb access like the warning shows:
`
SUBSYSTEM=="usb", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="3000", GROUP="plugdev"`

But still didn't work. After searching for a bit I learned that in Arch Linux the group plugdev does not exist. (See: https://bugs.archlinux.org/task/68533)

So the fix was to replace it with `TAG+="uaccess"` (See: https://bugs.archlinux.org/task/47205)

`SUBSYSTEM=="usb", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="3000", TAG+="uaccess"`

And it works perfectly! I don't know if it works with other distros but at least is the right one to use in Arch.

Could you add a warning to clarify that that udev rule does not work in all distros and maybe has to be changed?

**Comment by daniarla** [comment]
I tried the updated method and got not access to the usb:

> ```
>  # cat /etc/udev/rules.d/99-NSRCM.rules 
> SUBSYSTEM=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7321", MODE="0666"
> ```

I think that you meant :
`SUBSYSTEM=="usb", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="3000", MODE="0666"`

I had to maintain ATTRS{idVendor} & ATTRS{idProduct} from before to get it to work, but `MODE="0666"` works otherwise!

**Comment by daniarla** [comment]
Like before, I didn't read carefully and use the same udev rule from `NSRCM` in `NS` and got an error. Fixed now. Sorry for reopening this!

**Comment by dweipert-3138720606** [comment]
On Arch I kept getting
```
Steps to set 'udev' rules:
root # vim /etc/udev/rules.d/99-NS.rules
SUBSYSTEM=="usb", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="3000", GROUP="plugdev"
root # udevadm control --reload-rules && udevadm trigger

	at nsusbloader.com.usb.UsbConnect.openDevice(UsbConnect.java:167)
	at nsusbloader.com.usb.UsbConnect.connectHomebrewMode(UsbConnect.java:85)
	at nsusbloader.com.usb.UsbCommunications.run(UsbCommunications.java:54)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

although I added that.

I recently also had [fluffy-switch](https://aur.archlinux.org/packages/fluffy-switch) installed and removed it a couple days ago. Before that it was working.

It seems like [python-pyusb](https://archlinux.org/packages/?q=python-pyusb) is necessary for a connection. After just installing that package it's working again.

**Comment by developersu** [comment]
No, you don't have install python-things for this. But you have to add this:
```
SUBSYSTEM=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7321", MODE="0666"
```
To the file located at `/etc/udev/rules.d/99-NS-RCM.rules`

After this, you could reboot OR run as root `udevadm control --reload-rules && udevadm trigger`
