### ISSUE TITLE
Download produces a WinRAR file instead of an executable .jar

### ISSUE THREAD

**Issue by jp25130** [developersu/ns-usbloader#122]
**Describe the bug (mandatory)**
When downloading ns-usbloader-5.2.jar, it shows up in my Documents as ns-usbloader-5.2 in WinRAR form. Upon opening the WinRAR file, it shows as multiple folders (com, javafx, META-INF, native, etc.). I cannot locate the actual .jar file. I have downloaded Java JRE, but can't locate the application to open it with.

**Information about environment (mandatory):**
 - Windows 10 x64
 - Java Version 8 Update 333

**Steps to reproduce**
1. Download ns-usbloader-5.2.jar from GitHub
2. Application shows up as a WinRAR file with extractable folders
3. Does not download as an executable .jar with Java

**Expected behavior**
An executable .jar with Java

**Screenshots and/or information from application log**
https://imgur.com/MZORY0M

**Did you see this issue in previous versions?**
No

**Additional context**
Any help is appreciated, thank you! I know very little about programming - all I've learned is from guides online.

**Comment by Masamune3210** [comment]
Just change the file extension from rar to jar and it should work

**Comment by developersu** [comment]
You can just reinstall JRE/JDK to solve this or assign jar files manually like this: https://stackoverflow.com/questions/8511063/how-to-run-jar-file-by-double-click-on-windows-7-64-bit

**Comment by developersu** [comment]
Not a real bug. Closing.
