### ISSUE TITLE
Can trick into selecting a folder for transfer and not the ROMs inside it

### ISSUE THREAD

**Issue by PKGaspi** [developersu/ns-usbloader#129]
**Describe the bug (mandatory)**
When the option to select folders instead of files is turned on, it's possible to have a folder selected for transfer if the name ends with *.nsp (and probably other extensions too).

**Information about environment (mandatory):**
 - OS: Arch Linux 5.19.7-arch1-1
 - Java version [run 'java -version']: openjdk version "18.0.2" 2022-07-19

**Steps to reproduce**
1. Go to settings
2. Activate the option "Select folder with ROM files instead of selecting ROMs individually".
3. Go back to main tab.
4. Have a folder named "whatever.nsp" with .nsp files inside it.
5. whatever.nsp will appear in the selected ROMs list, with a size of 0.0B. The files inside this folders do not appear in the list.

**Expected behavior**
Folders should not be listed in the ROMs list, and the ROMs inside this folder should be instead.

**Did you see this issue in previous versions?**
Don't know

**Additional context**
It's possible that this happens with other installable file extensions as well.

**Comment by developersu** [comment]
Thank you for reporting!

**Comment by developersu** [comment]
Checked this. Actually it's fine. This needed for handling split-files, which are actually folders and ends on '.nsp', '.xci' etc.
So leaving it as is. 
It's like, for instance, it you rename '.mp3' file to '.nsp' and add it it'll also appear in app.
