### ISSUE TITLE
Skip kernel driver attach & detach (ERROR_NOT_SUPPORTED)

### ISSUE THREAD

**Issue by vivid2234** [developersu/ns-usbloader#136]
\[ PASS ] Found your OS: Windows 10
[ INFO ] Skip kernel driver attach & detach (ERROR_NOT_SUPPORTED)
[ FAIL ] Unable to get device ID

         Nothing has been sent to NS. Execution stopped.

**Comment by developersu** [comment]
1. Re-install drivers 
2. Use another cable
3. Use another port
