### ISSUE TITLE
Stuck in this page after updating JDK (affects both version 7.0 and 6.1)

### ISSUE THREAD

**Issue by dothackjhe** [developersu/ns-usbloader#137]
**Describe the bug (mandatory)**
Stuck on the page which shows the app's logo in the middle.

**Information about environment (mandatory):**
 - Windows 10 x64
 - Java version 19.0.2

**Steps to reproduce**
1. Simply run "ns-usbloader-7.0.jar/ns-usbloader-6.1.jar" or the ".exe" one 

**Expected behavior**
The app should run properly.

**Screenshots and/or information from application log**
![NS-USBLoader](https://user-images.githubusercontent.com/18740174/219534177-ac187f3d-082c-4206-a8ed-9e6861c1e0ad.PNG)

**Did you see this issue in previous versions?**
Initially, no. But since updating JDK to the latest, the same issue arose with version 6.1.

**Comment by developersu** [comment]
@dothackjhe if it's jar, run `java -jar ns-usbloader-7.0.jar -c`. Then execute again.

**Comment by dothackjhe** [comment]
> @dothackjhe if it's jar, run `java -jar ns-usbloader-7.0.jar -c`. Then execute again.

This fixed it! :D

**Comment by developersu** [comment]
You're welcome =)

(It just removes all application setting. In your case window size properties were too big.)
