### ISSUE TITLE
help: Failed to connect to socket

### ISSUE THREAD

**Issue by J-Kappes** [developersu/ns-usbloader#149]
I followed the instructions for setting up non-root-use literally. If I was supposed to switch out anything, it was not made clear.

Now when I run ns-usbloader as non-root I get the following error:
`
(java:15648): dbind-WARNING **: 18:31:21.158: Couldn't connect to accessibility bus: Failed to connect to socket /root/.cache/at-spi/bus_0: Permission denied
`

**Comment by developersu** [comment]
You should be able to use sockets starting from 1024 as non-privileged user. Usually. If you can't then it's some specific of your Linux distribution.
