### ISSUE TITLE
SysDVR Driver Delete After ns-usbloader Driver dowland how to

### ISSUE THREAD

**Issue by LilCiro** [developersu/ns-usbloader#152]
**Describe the bug (mandatory)**
I was using SysDVR at the time, how do I delete it, install it, download the driver from the settings, click on the drivers to install it, it was not solved, it says Android bootloader interface in the device manager, how can I solve it?

**Information about environment (mandatory):**
 - OS: Windows 11 64 Bit 
 - Java version 8 update 371 64 Bit

**Steps to reproduce**
Nope 

**Expected behavior**
Transfer games from USB

**Screenshots and/or information from application log**
https://github.com/developersu/ns-usbloader/assets/94236924/b8796adb-ebc9-4cec-a525-d7dbd353332d

**Did you see this issue in previous versions?**
No

**Additional context**
Nope

**Comment by developersu** [comment]
@LilCiro you won't see NS in list of devices by only plugging it in. It will appear as a new device in the list when you either
* (re)booted device in RCM mode (display is black)
* executed Goldleaf or Awoo or something like Awoo installer

So I guess you have to just plug NS into your PC, open Goldleaf or Awoo and right after that (before clicking anything else on your NS) check list of devices. You'll see new device appeared under 'libusbK' category.

Hope it helps ;)

**Comment by LilCiro** [comment]
My NS Oled chipped

**Comment by developersu** [comment]
Glad it's fixed!
