### ISSUE TITLE
Compatibility Issue on ARM-Based Mac with NS-USBLoader

### ISSUE THREAD

**Issue by migilion** [developersu/ns-usbloader#155]
**Describe the bug (mandatory)**
I'm encountering compatibility issues while running NS-USBLoader on my ARM-based Mac with an Apple M2 Max processor. The application seems to encounter errors related to architecture-specific libraries and JavaFX components when attempting to launch.

**Information about environment (mandatory):**
    OS: macOS with Apple M2 Max processor
    Java version: "21.0.1" 2023-10-17 LTS

**Steps to reproduce**
1. Attempt to run NS-USBLoader on an ARM-based Mac.
2. Encounter errors related to architecture-specific libraries and JavaFX components.

**Expected behavior**
The application should run without encountering errors related to architecture-specific dependencies.

**Screenshots and/or information from application log**
information from application log: Error: Loading 'prism_es2' library failed due to incompatible architecture: 'x86_64' needed, but 'arm64' encountered. JavaFX components encountering architecture-specific issues.

**Did you see this issue in previous versions?**
No, this is the first version I've tried on an ARM-based Mac.

**Additional context**
I've tried the ARM64 version of NS-USBLoader but continue to face errors related to architecture-specific libraries. I've also updated my Java version to the latest compatible with ARM64 architecture, yet the issue persists. Any guidance or an updated version specifically optimized for ARM-based systems would be greatly appreciated.

**Comment by developersu** [comment]
Use either JDK for arm architecture or regular ns-usbloader compiled for x86 (has no m1 postfix).

Check what JDK you use by executing `java -version` in terminal.

There are also pinned issue in github with discussion around best choice for apple silicon. If I recall correctly Azul is a good choice in your case.

**Comment by migilion** [comment]
regular ns-usbloader worked with Azul. Thank you!
