### ISSUE TITLE
cannot download the usb driver

### ISSUE THREAD

**Issue by cornradio** [developersu/ns-usbloader#156]
**Describe the bug (mandatory)**
cannot download the driver using interface

**Information about environment (mandatory):**
 - OS: windows 11
 - Java version ： i use exe installer

**Steps to reproduce**
1. Go to 'setting - download dirver 
2. stuck ( bad net work in china )
3. stuck forever

**Expected behavior**
If download the program through a system proxy, or give a way to download it manually, I can complete the driver installation

**Comment by developersu** [comment]
Many thanks for this!

It's not network, it's github™ 😐. Application downloads drivers from [here](https://github.com/developersu/NS-Drivers/releases/download/v1.0/Drivers_set.exe) and obviously it must be replaced to some independent and world-wide available location. 

Well, right now you can grab drivers from [computer in this room](https://git.redrise.ru/desu/NS-Drivers/releases/download/v1.0/Drivers_set.exe) as quick solution.

Maybe it's better to move this into Geetee or just embed into Windows version of the app.

Highly appreciate you bring this up

**Comment by cornradio** [comment]
i used proxifier Add javaw.exe using 127.0.0.1:8090
