### ISSUE TITLE
[Issue] .desktop entry is not working on Wayland (Clear Linux OS)

### ISSUE THREAD

**Issue by Cueropedo** [developersu/ns-usbloader#157]
**Describe the bug (mandatory)**
The program does work well if it's executed via the terminal, or using my .desktop entry on X11. But it doesn't work in Wayland, only if it's executed via the terminal.

**Information about environment (mandatory):**
 - OS: [Clear Linux OS 40390]
 - Java version [OpenJDK 19.0.2, but behaves the same with other versions]

**Steps to reproduce**
1.Use Wayland
2.Try to launching via a .desktop file, it will not work
3.Try using the same command that the .desktop file uses in "exec" and it will work. This problem does not happen in X11 and works flawlessly via the .desktop file.

**Expected behavior**
Launch via the .desktop file, just like X11 does.

**Screenshots and/or information from application log**
[Screencast from 2023-11-25 15-13-22.webm](https://github.com/developersu/ns-usbloader/assets/64707859/0a9fd03d-cef1-417b-a7f3-8469dbdb20ad)
[Screencast from 2023-11-25 15-16-17.webm](https://github.com/developersu/ns-usbloader/assets/64707859/da1e8a52-0736-4f75-8ee8-33468a07a7df)

I think one of the videos looks corrupt, but the other one shows the problem in Wayland, the one that's corrupted is the one running on X11 (and it's fine, doesn't have issues)

**Did you see this issue in previous versions?**
No

**Additional context**
Add any other context about the problem here

**Comment by developersu** [comment]
Maybe add `... -Djdk.gtk.version=2 ...` argument to the .desktop 'Exec' section like in this advice: https://github.com/developersu/ns-usbloader/issues/20

IDK, since it works once executed from terminal maybe some environment variable missed or something

**Comment by Cueropedo** [comment]
Unfortunately, it still doesn't work. I think I will just launch it via commands. Probably is a Java bug or something that's going to be fixed in the future.

**Comment by Cueropedo** [comment]
> Maybe add `... -Djdk.gtk.version=2 ...` argument to the .desktop 'Exec' section like in this advice: #20
> 
> IDK, since it works once executed from terminal maybe some environment variable missed or something

Dunno what you did in the last update, but now it works perfectly and I don't need to use the command-line anymore. My .desktop is working :)
