### ISSUE TITLE
Virus.Agent

### ISSUE THREAD

**Issue by jibanyan-mallow** [developersu/ns-usbloader#159]
I cant open the installer beacause my pc thiks its a virus.

 OS: Windows 10 x32bit

I just wanted to download the installer but my pc unter doesnt want to download it at all i tried anything but my PC says the risk for this trojan to break my pc  is so high that my pc just doesnt want to download it.

![Unbenannt](https://github.com/developersu/ns-usbloader/assets/155124433/2c1da29e-f8f7-4dc6-8a38-7f93eaf71d24)
the screenshot is in german

does anyone has the same issue?

**Comment by Masamune3210** [comment]
If you go to the actual downloads page in whatever browser you are using (looks like chrome), there might be an option to download anyway. Report it as a false positive, nothing about this project is malicious, AV vendors just don't quite understand the concept that not everybody can afford a codesigning cert and that heuristics arent everything
