### ISSUE TITLE
[update] pt-br language fix some misspelling

### ISSUE THREAD

**Issue by almircanella** [developersu/ns-usbloader#17]
updated portuguese text here:

https://pastebin.com/EdSYRBSw

some special simbols got messed up, i dont know if must change back all of it (transfer\u00EAncia = transferência). Or if leave as it.

**Comment by almircanella** [comment]
some special simbols got messed up, i dont know if must change back all of it (transfer\u00EAncia = transferência). Or if leave as it.

**Comment by developersu** [comment]
I'll update it. Thanks!

**Comment by developersu** [comment]
Also to convert from java-unicode to normal and back you can use this tool: https://itpro.cz/juniconv/
"Faz isso não mano!" That's awesome man, I love it! :D
