### ISSUE TITLE
Not Working on MacBook "NS not found"

### ISSUE THREAD

**Issue by niklasfink** [developersu/ns-usbloader#19]
Hey, unfortunately the usbloader is not working for me.
I have Goldleaf on my NS, put it in USB Installation mode where it says waiting for USB connection.
When I then plug in the USB-C cable (one end in the NS, one USB-C end into MacBook) and try to upload to NS, i always get this:

[ INFO ] 	Start chain
[ PASS ] libusb initialization
[ PASS ] Get device list
[ FAIL ] NS in connected USB devices not found
[ INFO ] Requested context close
[ INFO ] 	End chain

I'm on macOS 10.14.5 Mojave and have openjdk 11.0.2 installed.

**Comment by niklasfink** [comment]
Problem seems to be related to the direct connection via USB-C on both side. If I use a USB-Hub and then use USB-A to USB-C it works.

**Comment by NicoLeOca** [comment]
by chance I have a hub that I can use
thanks for the tip I wouldn't have found
