### ISSUE TITLE
Feature: batch upload with goldleaf or tinfoil

### ISSUE THREAD

**Issue by mtoensing** [developersu/ns-usbloader#21]
Maybe this has been asked before: I am on a mac and I can upload NSP files to my switch with goldleaf fine. I can select multiple NSP files, too. But how can I batch upload many nsp files at once? Is this a setting in goldleaf that it accepts more files or is this impossible at the moment?

**Comment by developersu** [comment]
It's limitation of the GoldLeaf, I can't change this architecture.
Thanks!

**Comment by mtoensing** [comment]
Does it work with tinfoil?

**Comment by developersu** [comment]
Yes
