### ISSUE TITLE
XCI install

### ISSUE THREAD

**Issue by chronoss09** [developersu/ns-usbloader#22]
I want to know how to install XCI file on NS-USBLoader, i use Tinfoil but no xci are loaded in Tinfoil :(

**Comment by developersu** [comment]
Only by converting XCI to NSP first. 
Just because XCI is not supported by Tinfoil. But XCI would be (?) supported by DBI (it's another NSP installer on switch side that uses same USB commands during installations).

**Comment by chronoss09** [comment]
Have you a link for DBI Installer ?
