### ISSUE TITLE
Cant install any NSP

### ISSUE THREAD

**Issue by PwnedC99** [developersu/ns-usbloader#23]
Tried both Tinfoil and Goldleaf and I get this error:

[ FAIL ] Data transfer (write) issue
  Returned: ERROR_PIPE

I tried various NSPs and also have the latest drivers and tried multiple ports.
It worked with my Mac though but with my PC it didnt work at all. I tried Windows and Hackintosh on my PC both gave me the same error.

**Comment by developersu** [comment]
Did you install libusbK using Zadig?
What is Windows version?

**Comment by developersu** [comment]
I assume it's fixed somehow or nobody cares. Closed.
