### ISSUE TITLE
gracefully handle errors

### ISSUE THREAD

**Issue by tycho01** [developersu/ns-usbloader#24]
when running the program without `sudo`, attempting to send over a game yields a udev permission error:
```
Files to upload:
[...]
[ INFO ] 	Start chain
[ PASS ] libusb initialization
[ PASS ] Get device list
[ PASS ] Read file descriptors for USB devices
[ PASS ] NS in connected USB devices found
[ FAIL ] Open NS USB device
  Returned: ERROR_ACCESS
[ INFO ] Double check that you have administrator privileges (you're 'root') or check 'udev' rules set for this user (linux only)!
```

While adding sudo helps me work around this (which probably isn't the right way), it's only when one thinks to open the logging tab that one realizes there has been an error, rather than it just being busy still trying to do something.
Moreover, the interrupt button becomes unresponsive here.

It would be nice if on error the tab view could switch to the logging tab once an error is printed.
Additionally, it would be helpful if the interrupt button could still be used after receiving an error as well. (Current workaround: kill/restart)

**Comment by developersu** [comment]
Good catch! Thanks!

**Comment by developersu** [comment]
> when running the program without sudo, attempting to send over a game yields a udev permission error:

Fixed. Added more detailed guide how to avoid this situation in case it happened on 'Log' tab.

> It would be nice if on error the tab view could switch to the logging tab once an error is printed.

Not added (But it's a good notice! I'm still in doubts to add it or not.)

> Moreover, the interrupt button becomes unresponsive here.

> Additionally, it would be helpful if the interrupt button could still be used after receiving an error as well. 

Partly fixed, will continue working on this direction.
