### ISSUE TITLE
Support for goldleaf 0.6.1?

### ISSUE THREAD

**Issue by eb0687** [developersu/ns-usbloader#25]
Will this work with gold leaf v0.6.1?

**Comment by developersu** [comment]
Yes

**Comment by thedmelik** [comment]
How can this be used with GL 6.1? I no longer see a USB install option?

Thanks.

**Comment by developersu** [comment]
It would work perfectly! Today or tomorrow ;)

(using 'Explore content' -> 'Remote PC (via USB)')

⁣Отправлено с помощью TypeApp ​

На 13 Авг 2019 г., 2:20, в 2:20, thedmelik <notifications@github.com> написал:п>How can this be used with GL 6.1? I no longer see a USB install option?

**Comment by thedmelik** [comment]
Thanks You.

**Comment by Trunkzeh** [comment]
Utilising ns-usbloader 0.5.2 with goldleaf 0.6.1; simply selecting the Remote PC option via Switch does nothing but 'crash' Goldleaf. Removing the USB cable crashes atmosphere. Running usbloader on mojave 10.4.6

**Comment by developersu** [comment]
@Trunkzeh you're just in time =)

Try this https://github.com/developersu/ns-usbloader/releases/tag/v0.6

**Comment by thedmelik** [comment]
Thank you all. Excited to try this out right now.

**Comment by thedmelik** [comment]
Thank you all; the new release works like a charm with GL 6.1.
