### ISSUE TITLE
Can't connect switch to mac via USB.

### ISSUE THREAD

**Issue by malbernaz** [developersu/ns-usbloader#27]
I know it's not specific to your project, but do you have any tips for this case? I've been trying to use ns-usbloader for like a week with no success.

**Comment by developersu** [comment]
I don't understand what do you mean. Describe each step you're doing.

**Comment by malbernaz** [comment]
Thanks for your quick response! I don't know what was happening exactly, but I wasn't being able to connect the switch to my computer (mb pro 15inch 2018). My guess is that it was being recognised as a power source. Once I've connected the computer to a real power source and hooked my switch via a secondary usb It was immediately recognized.

Thanks for your software.
