### ISSUE TITLE
Connect to macos

### ISSUE THREAD

**Issue by jul2003** [developersu/ns-usbloader#28]
Hi ,

I try to use your software from my MacBook pro to send my xci's cartdridge backup to my switch.
I use latest tinfoil on the switch , i open tinfoil , i select the file and press send to ns but nothing happen on the switch.
Can you tell me what i'm doing wrong ?
Do i need to install something specific on the MacBook ? I use this adapter https://www.amazon.fr/dp/B0776R9CJ8/ on the MacBook and then switch i have a usb a - usb c cable.

Thanks

Jul

**Comment by developersu** [comment]
Hi,
Sure. This is what could be a problem:
1. You're trying to upload XCI using TinFoil (it's not supported).
2. You're using non-supported Tinfoil.

**Comment by Trunkzeh** [comment]
@jul2003 Please use the latest version of ns-usbloader (0.6) and Golfleaf (0.6.1) and you will have no problems. I'm running the above set-up on Mojave 10.14.6; just make sure you have Java installed otherwise ns-usbloader wont run.

**Comment by jul2003** [comment]
Thanks.
As goldleaf doesn't support xci i need to convert to nsp.
I have setted up a ftp server with my xci's cartridge backup and add it as a source on tinfoil and this is working;
I'll come back later to the ns-usbloader solution.
Issue can be closed.
