### ISSUE TITLE
error when using install with goldleaf in mac mojave

### ISSUE THREAD

**Issue by rikimm** [developersu/ns-usbloader#3]
The installer in tinfoil works without problems, the problem is in goldleaf, for some reason when you install a game, almost when you finish installing the game you disconnect from the console and start looking for some communication, and even get to lock my mac, opting do the test with tinfoil and it worked, but I congratulate you as it is the only tool that has worked for me to install the nsp on mac

**Comment by developersu** [comment]
I'm almost 100% sure that the issue is in GoldLeaf. I also saw what you're talking about while TinFoil worked as expected and GL is not. Even with official GoldTree.

**Comment by rikimm** [comment]
ok then i will continue using the TinFoil 

regards.

**Comment by developersu** [comment]
Yeah, for now I highly recommend TinFoil.

**Comment by FabrizioA** [comment]
I've the same problem.. it's very strange... GoldLeaf works ok with GoldTree on Windows... but not on MacOS :'(
Any news?

**Comment by developersu** [comment]
Regarding what? Latest GoldLeaf-0.5 and NS-USBloader-0.4 should work as expected on MacOS Mojave. Isn't they?

**Comment by FabrizioA** [comment]
Hi,

In my MacBook Pro with Mojave I have download NS-USBLoader with JDK 12, the application opens correctly but when I connect my NS the application doesn’t recognize it....
If I select GoldLeaf then the USB button remains disabled and if I select the button to push the nsp I get an error.
Maybe I’m using the wrong versione of jdk??

:(



Inviato da iPhone

**Comment by developersu** [comment]
@FabrizioA 
You have to add NSP files, select GoldLeaf in drop-down. Then 'upload' button become active. So after this you have to connect NS to your computer, open GoldLeaf and select 'something-something USB install I don't remember to be honest' and click 'upload'. 
You may also copy log-output in here if you want.
As for JDK, it was not tested on JDK12 but I don't think that it's a problem.

**Comment by FabrizioA** [comment]
Thank you, I’ll try it ASAP ;)

**Comment by FabrizioA** [comment]
IT works like a charm! ;)
It was my mistake … sorry.

Thank you
F.

**Comment by developersu** [comment]
@FabrizioA   glad to hear that it works =)
Thanks!
