### ISSUE TITLE
Enable non-NSP files to be selected and transferred through Goldleaf

### ISSUE THREAD

**Issue by satelliteseeker** [developersu/ns-usbloader#33]
With the option to select "All Files" for Goldleaf, it will allow easy transfer of .nro applications, saves, media and other files by using Goldleaf's "Copy" command.

src/main/java/nsusbloader/Controllers/NSLMainController.java:130:

```
if (FrontTabController.getSelectedProtocol().equals("GoldLeaf")) {
    fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("All Files", "*.*"));
}
```

**Comment by developersu** [comment]
ok
