### ISSUE TITLE
Fails to autodetect system IP Address on macOS Catalina

### ISSUE THREAD

**Issue by terraphantm** [developersu/ns-usbloader#45]
The application detects the local IP address as 0.0.0.0 and fails to trasnfer files to the Switch. If I manually enter the system's IP address, things work properly otherwise. Using jdk 13.0.1

**Comment by developersu** [comment]
Thank you for reporting! Not sure that I could provide quick fix for this, but once I find something with Catalina I'll check it =)

**Comment by developersu** [comment]
Should be fixed on v2.1
