### ISSUE TITLE
xci for ns-usbloader ?

### ISSUE THREAD

**Issue by azoreseuropa** [developersu/ns-usbloader#48]
Why not add xci ? I know it came with xci for Awoo installer. However, why dont you add xci for your own ns-usbloader? Select files, Select split nsp, then why not Select XCI to the third option ? It will be nice. Love your GUI, by the way!

**Comment by developersu** [comment]
Click 'Settings' (Gear)
Click on checkbox 'Allow XCI / NSZ / XCZ files selection for Tinfoil' under the 'Tinfoil' section.

**Comment by developersu** [comment]
And thank you. Nice to know that someone likes GUI :)
