### ISSUE TITLE
Gets killed when installing nsp

### ISSUE THREAD

**Issue by LightningLogicLabs** [developersu/ns-usbloader#52]
**Describe the bug (mandatory)**
Attempt to install nsp results in ns-usbloader freezing then getting killed

**Information about environment (mandatory):**
 - OS: Ubuntu 19.10
 - Java version 14

**Steps to reproduce**
1. java -jar ns-usbloader-0.8.jar
2. Select goldleaf in drop down menu
3. select nsp to upload
4. open goldlead on switch
5. click upload to ns
6. go to explore content
7. go to Remote PC (via USB)
8. enter VIRT folder
9. select nsp
10. install
11. Wait a few seconds, ns-usbloader gets killed

**Expected behavior**
To install the NSP I selected

**Did you see this issue in previous versions?**
Don't know, used a mac before, same version im using in ubuntu (v 0.8)

**Comment by developersu** [comment]
Thanks for the report!
Same to #40
