### ISSUE TITLE
Install NSP Error on Mac OS Using NS-USBLoader

### ISSUE THREAD

**Issue by bezicxt** [developersu/ns-usbloader#53]
Hi 
When I try to install NSP in tinfoil or gold leaf, it gives me this error:

 INFO ] Free device list
[ INFO ] Skip kernel driver attach & detach
[ PASS ] Set active configuration to device.
[ FAIL ] Claim interface
         Returned: ERROR_OTHER
[ WARN ] Release interface
         Returned: -5 (sometimes it's not an issue)
[ INFO ] Requested handler close
[ INFO ] Requested context close
[ INFO ] 	End chain

for NS, I am using latest Gold leaf version 0.8
My MAC OS is Sierra.

Kindly advise.

**Comment by developersu** [comment]
Hi, 
Do you use '-legacy' build?

**Comment by developersu** [comment]
I guess you've fixed this somehow. Closed.
