### ISSUE TITLE
libusbk installation only succeeds when using the non-WCID driver

### ISSUE THREAD

**Issue by Dinxton** [developersu/ns-usbloader#56]
The Windows prerequisite instructions under (["Usage"](https://github.com/developersu/ns-usbloader#windows)) state to install the WCID version of the libusbk driver using Zadig, but on two devices so far (both Windows 10, 1909, 18363.752), I've only had the driver successfully install when using the 'Install Driver' option.

### Info:
- NS-USBloader v2.2 (non-legacy)
- Awoo v1.3.2
- Java version: Oracle JRE 8u251
- OS: Windows 10, 1909 (18363.752) on both devices
- Zadig version: 2.5
- USB: USB A to C 3.0 cable connected to USB 3.0 port; also reproducible when connected to USB 2.0

### To reproduce:
- On a system with no drivers installed, open Awoo installer and connect Switch to PC.
- Open Zadig and select 'Nintendo Switch' from dropdown (without 'List all Devices' selected)
- Click the dropdown on the right and tick 'Install WCID Driver'
- Click install, and the installation succeed.
- Device manager doesn't show the new libusbk driver or section, and Awoo doesn't detect NS-USBloader.

If 'Install Driver' is selected instead, the driver installation succeeds, the device manager group is created and displayed, Awoo detects NS-USBloader and installation succeeds.

Has something changed in more recent Windows 10 builds that has stopped the WCID drivers from working?

**Comment by developersu** [comment]
To be honest I have no idea. Maybe it's just a typo.
