### ISSUE TITLE
Unable to upload files

### ISSUE THREAD

**Issue by KeepYourPantsOff** [developersu/ns-usbloader#58]
When I click on "Select files"nothing happens.
Same with "Select split NSP"

I was uploading files to my Switch fine a moment before when it suddenly stopped working.

- Restarted my computer
- Restarted Switch
- Updated USBloader to v2.2
- issue remains

Running Windows 10, v1909 - 64 bit

**Comment by developersu** [comment]
Try this:
1. Run 'regedit.exe'
2. Go to **HKET_CURRENT_USER -> Software -> 'JavaSoft' -> 'Prefs'**
3. Remove entry (folder) **'/N/S-/U/S/Bloader'**

**Comment by developersu** [comment]
On versions since 3.0 use 'java -jar thisApp.jar -c' OR 'java -jar thisApp.jar --clean' to remove settings
