### ISSUE TITLE
Returned: ERROR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by XargonWan** [developersu/ns-usbloader#6]
I have got an error with v0.3:

Files to upload:
  C:\PATH\Carcassonne [Carcassonne - Inns & Cathedrals] [0100C9200A9C3003][v0].nsp
[ INFO ] 	Start chain
[ PASS ] libusb initialization
[ PASS ] Get device list
[ PASS ] Read file descriptors for USB devices
[ PASS ] NS in connected USB devices found
[ FAIL ] Open NS USB device
  Returned: ERROR_NOT_SUPPORTED

On the switch nothing happens, just says USB is ready, so basically is waiting.
0.2.2 has no issues.

Windows 10

**Comment by developersu** [comment]
Which OS do you use?

**Comment by developersu** [comment]
Ok.. will make another build for Win10 later today that fixes this issue.
Not clear why only you reported this issues.. there should be a lot of people.
Thanks!

**Comment by developersu** [comment]
@XargonWan 
What Windows 10 do you use? Is it x86 or x86_64?
What version of libusbK installed? (driver you installed with Zadig)

Check this. Should work for you.
https://drive.google.com/file/d/1eKwUDkm7EsIV1TW3ejdOyosm5kXu_FUo/view

**Comment by developersu** [comment]
And get back to me with results if it works please.

**Comment by cengicadis** [comment]
i have the same problem like this guy. I test your new version but still the same. I use windows 10 enterprice x64

**Comment by developersu** [comment]
@cengicadis check file attached on the link above and let me know if it works for you.
Also, is it worked before?

**Comment by developersu** [comment]
People, I really appreciate that your're reporting issues, but could you provide more information please? Or just back to this page time-to-time..
Like what USB (usb-3/usb-2) cord used, is the linked version works for you or not, are you plugging your NS to PC USB-3 or not, into the 'chargeable' USB port or into the regular one?

**Comment by developersu** [comment]
I assume nobody is gonna leave me anything in addition for this defect. 
Closing.

**Comment by Supporterino** [comment]
Hey developersu,

just a little notice i faced this error as well on the newest release 0.5.1. Using win 10 pro via USB-C to USB-C Connection. The experimental build from link above is working

**Comment by developersu** [comment]
Hi Supporterino,
Check updated release. It should be working for you (alternative build): [https://github.com/developersu/ns-usbloader/releases/tag/v0.5.1](https://github.com/developersu/ns-usbloader/releases/tag/v0.5.1)

And thank you for reply!!

**Comment by miguel-mc** [comment]
@developersu I'm getting the same chain of messages on the alternative build of 0.8 using windows 10 pro

**Comment by developersu** [comment]
@miguel-mc it's strange. Well, use regular version then.

**Comment by DarthPao** [comment]
i got the same chain with the alternative build that you sent.
[ INFO ] 	Start chain
[ PASS ] libusb initialization
[ PASS ] Get device list
[ PASS ] Read file descriptors for USB devices
[ PASS ] NS in connected USB devices found
[ FAIL ] Open NS USB device
  Returned: ERROR_NOT_SUPPORTED

**Comment by twig** [comment]
Go to NS-USBLoader > Settings > Click "Download & install drivers"

Follow the prompts and it should update a driver. RCM inject worked for me after that (no reboot required)
