### ISSUE TITLE
Feature request: Batch merge

### ISSUE THREAD

**Issue by Corgano** [developersu/ns-usbloader#60]
Merging multi-part NSP's into a single file takes some time, and it would be nice to be able to select MULTIPLE folders and bulk merge them, one after another.

**Comment by developersu** [comment]
It's possible using CLI:
`$ java -jar app.jar -m /save/to/dir /path/to/splitfile1.nsp /path/to/splitfile2.nsp ... /path/to/splitfileN.nsp`

No updates for GUI. Will consider adding this feature later.

**Comment by developersu** [comment]
Fixed since v5.1
