### ISSUE TITLE
Cant send files via USB on OS X

### ISSUE THREAD

**Issue by juato4** [developersu/ns-usbloader#66]
**Describe the bug (mandatory)**
I can't send files via USB on Mac OS X... seems like the switch isn't recognized... 

I can via WIFI

**Information about environment (mandatory):**
 - OS X 11
 - Java version [LAST]

**Comment by developersu** [comment]
IDK. Attach application logs and I'll look.

**Comment by juato4** [comment]
> IDK. Attach application logs and I'll look.

Archivos a subir:
 /Users/juancruzpagnutti/Downloads/Jump Rope Challenge [0100B9C012706000][v0]BASE.nsp
[ PASS ] NET: Host IP detected as: 192.168.0.19
[ PASS ] NET: Your port detected as: 6703
[ INFO ] 	Start chain
[ PASS ] Initiation files list has been sent to NS.
[ INFO ] Reply to range: 256-259
[ INFO ] Replying for requested file: Jump Rope Challenge [0100B9C012706000][v0]BASE.nsp
[ INFO ] Reply to range: 0-15
[ INFO ] Reply to range: 16-399
[ INFO ] Reply to range: 74990992-74994063
[ INFO ] Reply to range: 74990992-74994575
[ INFO ] Reply to range: 74994576-74995279
[ INFO ] Reply to range: 74995280-74997071
[ INFO ] Reply to range: 400-3471
[ INFO ] Reply to range: 400-73843087
[ INFO ] Reply to range: 73843088-73846159
[ INFO ] Reply to range: 73843088-74756495
[ INFO ] Reply to range: 74756496-74759567
[ INFO ] Reply to range: 74756496-74990991
[ INFO ] Interrupted by user.
[ INFO ] 	End chain

**Comment by juato4** [comment]
I think maybe, there isn't drivers for MAC. it seems like the program isn't recognizing the switch.

**Comment by juato4** [comment]
USB 3 maybe?

**Comment by developersu** [comment]
You've sent log of the successful transfer via 'Tinfoil/NET'. I need log with issue description for Tinfoil/USB or Goldleaf.

Yes, it could be a problem with usb3  or this app defect or bug in used libraries.

**Comment by juato4** [comment]
Yes, because all successful transfer is via WIFI... usb is not recognized by ns-usbloader

**Comment by developersu** [comment]
So what do you see in logs  when you're  trying to use usb connection?

**Comment by juato4** [comment]
The logs didnt say anything about usb....

**Comment by developersu** [comment]
It should. Did you select USB in drop-down?

**Comment by juato4** [comment]
Yes... there is any file to upload?... it didnt say anything about usb... and I was tried.

**Comment by developersu** [comment]
IDK, add some file for upload. Once you trying to send nsp and it's failed you can see on logs why it's failed.

**Comment by juato4** [comment]
Sure.. please say me where to finde the file that you need and I will upload it.

**Comment by developersu** [comment]
I don't need it. You're saying that usb transfer doesn't work and now I have to tell you where should you get your files? I don't get it.

**Comment by juato4** [comment]
sorry, I understand bad... 

i was tried... the logs says anything.

**Comment by developersu** [comment]
Ok, add steps to reproduce, attach screenshots and add java version.

**Comment by juato4** [comment]
Mac: MacBook Pro 2018 Touch Bar ( OSX 11 )
Java Version 8, update 261, Compilation 1.8.0_261_b12

1. USB-C on both sides
2. ns-usbloader-4.0.jar excecuted 
3. Switch opened with Awoo
3- Awoo usb option pressed
4. Awoo says: ( NO USB CONNECTION DETECTED )

[https://ibb.co/L0TWGyL](url)
[https://ibb.co/Nx75gxL](url)

**Comment by developersu** [comment]
Most likely your USB cord is broken. Try another USB cable, then another USB port and (if nothing else helped) another PC. 
With ns-usbloader or even without it you have to see [something like this](https://i.imgur.com/ua0P5yO.jpg) on your NS.

Now Awoo Installer doesn't see ANY connection.

**Comment by juato4** [comment]
ok, other port worked fine!!!. 

Thanks!

**Comment by developersu** [comment]
Click 'Sent to NS'
If not helps, send screenshots with logs section.

**Comment by juato4** [comment]
Archivos a subir:
 /Users/juancruzpagnutti/Desktop/TINY METAL [010074800741A800][v262144] (0.39 GB).nsz
[ INFO ] 	Start
[ INFO ] Skip kernel driver attach & detach (ERROR_NOT_SUPPORTED)
[ INFO ] ============= GoldLeaf v0.8 =============
	VIRT:/ equals files added into the application
	HOME:/ equals /Users/juancruzpagnutti
[ INFO ] GL Execution interrupted
[ INFO ] 	End

**Comment by juato4** [comment]
Look the video: [https://www.dropbox.com/s/neldax3uc9xmcla/IMG_3078%202.MOV?dl=0](url)

**Comment by developersu** [comment]
Logs says that you're using Goldleaf but you're using Awoo Installer.  'Awoo Installer' uses the same command set to 'Tinfoil'.
Long story short: select Tinfoil/USB on the top. [Like this.](https://i.imgur.com/xILnIlK.png)

**Comment by juato4** [comment]
I can’t... usb option is greyed

**Comment by juato4** [comment]
WORKED!!! Thanks!

**Comment by developersu** [comment]
And always worked :sunglasses:
You're welcome!
