### ISSUE TITLE
The traditional Chinese translation

### ISSUE THREAD

**Issue by qazrfv1234** [developersu/ns-usbloader#68]
Hello,
ns-usbloader is amazing!
I completed the translation as the attachment. 

Many thanks! 
Leo

[The Traditional Chinese lang-file for ns-usbloader v4.1.zip](https://github.com/developersu/ns-usbloader/files/4977113/The.Traditional.Chinese.lang-file.for.ns-usbloader.v4.1.zip)

**Comment by developersu** [comment]
Thank you!

**Comment by qazrfv1234** [comment]
Hi, 
please send me the zh-rTW strings lang-file about ns-usbloader-mobile,
I'll translate as soon as possible.

Mail to qazrfv1234.q1@gmail.com 

Cheers,
Leo

**Comment by developersu** [comment]
Hi Leo,

All strings are here: https://github.com/developersu/ns-usbloader-mobile/blob/master/app/src/main/res/values/strings.xml

Appreciate your help!

**Comment by developersu** [comment]
Added since v4.2 Thanks!
