### ISSUE TITLE
MacOSX - NS not found in connected device

### ISSUE THREAD

**Issue by guskermitt11** [developersu/ns-usbloader#75]
After run ns-loader, I choose a game and when I click: Upload to NS, appears this error:

java.lang.Exception: NS not found in connected USB devices
	at nsusbloader.COM.USB.UsbConnect.findDevice(UsbConnect.java:136)
	at nsusbloader.COM.USB.UsbConnect.connectHomebrewMode(UsbConnect.java:82)
	at nsusbloader.COM.USB.UsbCommunications.run(UsbCommunications.java:54)
	at java.base/java.lang.Thread.run(Thread.java:834)

This doesn't occur in Windows 10 thru Parallels (It's too slow and I'm trying to use it from Mac).

**Comment by developersu** [comment]
Update this issue by adding information about environment

**Comment by guskermitt11** [comment]
MacOsx Catalina version 10.15.7
USB C connection.

I tried to debug it, but when I connect my Switch with Tinfoil running, appears a new idVendor and idProduct:

idVendor=5824
idProduct=10210

But default config is:

VENDOR_ID = 1406
PRODUCT_ID = 12288

**Comment by developersu** [comment]
Try it with JDK 11 on MacOS. AFAIK it's more stable.

Regarding your first VID/PID: they are is for something different. Second pair 1406/12288 is correct and set once running GoldLeaf, Awoo Installer, NSAInstaller etc.

**Comment by guskermitt11** [comment]
Using java 11 the problem is solved. 
Thanks!
