### ISSUE TITLE
Merge: Save to folder deleted

### ISSUE THREAD

**Issue by xXxQuiquexXx** [developersu/ns-usbloader#79]
**Describe the bug (mandatory)**
If the folder selected as the destination is deleted, the "change" button stops working and a new destination cannot be chosen.

* It took me a long time to realize that I had to re-create the folder for the button to work again and let me choose a new path

**Information about environment (mandatory):**
 - OS: Windows 10 x64
 - Java version [run 'java -version']: java version "1.8.0_271"

**Steps to reproduce**
1. Choose a destination folder
2. Delete the selected folder
3. Try to change the destination folder with the "change" button
4. the button does nothing

**Expected behavior**
The button should allow the destination folder to change even though the previously selected folder no longer exists

**Did you see this issue in previous versions?**
Yes

**Comment by developersu** [comment]
Fixed @ v4.4.

Thank you for so detailed report :)

**Comment by xXxQuiquexXx** [comment]
Thanks to you!
Excellent your work! ;)
