### ISSUE TITLE
XCI installation addition.. Can this add for macOS users too ?

### ISSUE THREAD

**Issue by azoreseuropa** [developersu/ns-usbloader#8]
http://tinfoil.io/#download

XCI is being addition. Can you add it to NS-USBloader so we can installed XCI as well ? Thanks.

**Comment by developersu** [comment]
Hi azoreseuropa!
Tinfoil my app supports is [Adubbz/Tinfoil](https://github.com/Adubbz/Tinfoil/) version 0.2.1 (whatever build you find in the internet OR compile by yourself)
I think it would be possible to use XCI files as well for upload into Adubbz/Tinfoil or XorTroll/GoldLeaf, but I did not made a good research to make it real. It's a big thing and requires time.

The link you provided, I guess, goes to blawar's TinFoil application. I'm not touching that with a sixty-foot pole.

Appreciate your interest in NS-USBloader and thank you for report!
