### ISSUE TITLE
Select NSP files not working

### ISSUE THREAD

**Issue by tefanga** [developersu/ns-usbloader#80]
**Describe the bug (mandatory)**
The button Select NSP files stopped working.
I've been using the app for installing like 20 games no problem. But last game I installed was South Park The Fractured but Whole, installed the update all fine, tried for the dlcs and button stopped working.
Closed and reopened still not working, system reboot still not working... also reinstalled java, still not working.
Some people told me that it could be because I deleted the last folder where the button redirect automatically when pushing it.
But if I did, I dont remember.

**Information about environment (mandatory):**
 - OS: Windows 10 - 64 bits
 - Java version: 1.8.0_271
 - Ns-usbloader version: 4.3 

**Steps to reproduce**
1º Install games (if app worked) 
2º Till you reach a game you can't "upload" to the ns-usbloader
3º Stopped working the nsp file button

**Expected behavior**
Expected for the file explorer opens correctly

**Screenshots and/or information from application log**

**Did you see this issue in previous versions?**
Don't know. Haven't used them

**Additional context**
Add any other context about the problem here
I had read other people has/had the same problem.
I think maybe as other people told me, it could be because I deleted the folder of the last place where I selected a file. (can't know that because I don't remember doing it)
Also I cleared the cache of java, still not working.

**Comment by developersu** [comment]
Yeah, it's fixed in code but I was too lazy to release new version ( ><)
Anyway, now (v4.4) it's fixed!

Many thanks for detailed report!

**Comment by tefanga** [comment]
Thank you for your answer/concern.
Great app.
Nice work.
