### ISSUE TITLE
Gentoo Linux required Java package

### ISSUE THREAD

**Issue by tantoinet** [developersu/ns-usbloader#9]
On Gentoo Linux, it seems that jre11 can be installed using **emerge virtual/jre:11**, or by enabling the unstable [oracle-jdk-bin-11.0.2](https://packages.gentoo.org/packages/dev-java/oracle-jdk-bin) in /etc/portage/package.accept_keywords, emerging it and using the /opt/oracle-jdk-bin-11.0.2/bin/java (if I recall well)

**Comment by developersu** [comment]
I assume this issue solved
