### ISSUE TITLE
Class not found on Windows 10 Pro  (20H2) x64

### ISSUE THREAD

**Issue by kangaroo72** [developersu/ns-usbloader#95]
Hi,

I'm starting ns-usbloader-5.0.jar, and I'm getting
`Fehler: Hauptklasse C:\Program Files\Java\jre1.8.0_291\bin\ns-usbloader-5.0.jar konnte nicht gefunden oder geladen werden`
well okay - it's german. quick'n short - main class not found...

Here the result of java -version
`java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)`

Did I something wrong?
Thank you

**Comment by developersu** [comment]
Hi

Try JDK 11. I think you're doing everything right. 
Actually double-click on jar should work (wherever it is).

**Comment by kangaroo72** [comment]
Hi,

I'm now on
`java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)`
Still no luck - any other idea?

**Comment by developersu** [comment]
Yeah. Run it from terminal and copy-paste everything you type and error that you see and stacktrace if it appears.

**Comment by kangaroo72** [comment]
Hi,
see here
`C:\Users\tescher\Downloads\Switch\NS-USBloader>ns-usbloader-5.0.jar
Error: Could not find or load main class C:\Users\tescher\Downloads\Switch\NS-USBloader\ns-usbloader-5.0.jar
Caused by: java.lang.ClassNotFoundException: C:\Users\tescher\Downloads\Switch\NS-USBloader\ns-usbloader-5.0.jar

C:\Users\tescher\Downloads\Switch\NS-USBloader>`

**Comment by developersu** [comment]
Ok, try this: `java -jar C:\Users\tom\Downloads\Switch\NS-USBloader>ns-usbloader-5.0.jar`

**Comment by kangaroo72** [comment]
`java -jar C:\Users\tom\Downloads\Switch\NS-USBloader\ns-usbloader-5.0.jar`
results in
`Error: Invalid or corrupt jarfile C:\Users\tom\Downloads\Switch\NS-USBloader\ns-usbloader-5.0.jar`

**Comment by kangaroo72** [comment]
It seems, File was broken... wtf?! :-P

![grafik](https://user-images.githubusercontent.com/6906390/118716357-04dfab00-b825-11eb-9afc-918a92bb670c.png)

**Comment by kangaroo72** [comment]
Thx so much for troubleshooting 👍
