### ISSUE TITLE
Can't click anything

### ISSUE THREAD

**Issue by alexgleason** [developersu/ns-usbloader#97]
**Describe the bug (mandatory)**
I launched the software and I straight up can't click anything. It goes straight through to whatever is behind it.

https://user-images.githubusercontent.com/3639540/124373635-90888c00-dc59-11eb-95e6-f2fe4042eed5.mp4

**Information about environment (mandatory):**
 - OS: elementary OS 5.1.7 Hera (Built on Ubuntu 18.04.4 LTS)
 - Java version:
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
```

**Comment by developersu** [comment]
Hi Alex!

Thank you for reporting this. 

I've never seen anything like this before and have no idea how to fix this.. Looks like an issue with windows manager and if so it should impact all JavaFX applications. Could you please try to run any other JavaFX based application to compare results?
And here I should leave some examples of JavaFX applications.. so.. let's say [konogonka](https://github.com/developersu/konogonka/releases), [Quark](https://github.com/XorTroll/Goldleaf/releases)

**Comment by alexgleason** [comment]
I tried konogonka and experienced the exact same thing (it clicks through to the window behind it). You think I should open an issue with my window manager?

**Comment by alexgleason** [comment]
I opened an issue with elementary OS: https://github.com/elementary/gala/issues/1174

**Comment by developersu** [comment]
Oh, well.. I don't know. Maybe it's java-world problem or something. 
Anyway, let's see what would they say.

**Comment by alexgleason** [comment]
Someone in the other thread commented it's because of `GTK_CSD=1`. Running it like this totally fixed it: 

```
GTK_CSD=0 java -jar ./ns-usbloader-5.0.jar
```

![Screenshot from 2021-07-08 21 52 16](https://user-images.githubusercontent.com/3639540/125016380-e5038100-e036-11eb-91e4-eb6dd6b5c8e3.png)

Seems it's an OS issue, so I'll close it.
