### ISSUE TITLE
Upload completed

### ISSUE THREAD

**Issue by andrei-zgirvaci** [developersu/ns-usbloader#99]
I am using Awoo installer and after I press upload from ns-usbloader and the installation is complete on my switch, does the NSP file gets cleaned after the installation or do I have to delete it manually?

**Comment by Masamune3210** [comment]
See comment on other issue, but basically no, there is no need as the nsp itself never actually gets copied to the switch

**Comment by andrei-zgirvaci** [comment]
Thank you for the detailed explanation!
